version : '3'

services:
  mysql:
    image: mysql:latest
    container_name: dev_mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: arca
  nginx:
    image: nginx:latest
    ports: 
        - 8080:80
    # volumes: 
    #     - nginx_data:/etc/nginx/conf.d
    #     - nginx_data/html:/usr/share/nginx/html
    container_name: nginx

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_USER: user
      PMA_PASSWORD: user
    restart: always
    ports:
      - 8183:80

  elasticsearch:
    image: docker.io/bitnami/elasticsearch:6.4.2
    volumes:
        - "elasticsearch_data:/bitnami/elasticsearch"
  kibana:
    image: docker.io/bitnami/kibana:6.4.2
    ports:
        - "5601:5601"
    volumes:
        - "kibana_data:/bitnami/kibana"
    depends_on:
        - elasticsearch
volumes:
  elasticsearch_data:
    driver: local
  kibana_data:
    driver: local
  nginx_data:
    driver: local
   